POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoYW90cnVvbmciLCJpZCI6IjYwM2Y3ZjI4ZTBmYzE5MTQ2ZTYwODBiNyIsImlhdCI6MTYxNTI3MDY3Mn0.EwNv-1aG12PdWZdYGfFioHghMew0MDTAi98I-EfLtS8

{
  "title": "tests middleware position",
  "author": "No name",
  "url": "https://middleware.com",
  "likes": 7

}