POST http://localhost:5001/api/login
content-type: application/json

{
     "email":"thao.truong@mail.com",
     "password":"mypassword"
}

# {
#     "username":"pauldenman",
#     "password":"mypassword"
# }